# Generated by Django 5.0.6 on 2024-05-18 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_plan_position',
            name='Event_Plan',
        ),
        migrations.RemoveField(
            model_name='event_plan_position',
            name='Event',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='Event_Plan_Position',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Event_Plan_Position',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='Team_Members',
        ),
        migrations.RemoveField(
            model_name='invitationstatus',
            name='Invitation',
        ),
        migrations.RemoveField(
            model_name='results',
            name='Invitation',
        ),
        migrations.RemoveField(
            model_name='invitationstatus',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='invitationstatus',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='team_list',
            name='Team',
        ),
        migrations.RemoveField(
            model_name='results',
            name='Team_List',
        ),
        migrations.RemoveField(
            model_name='team_members',
            name='Team_List',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='EducationLevel',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='EventType',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='Time_Submit',
            new_name='time_submit',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='Result',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='date_event',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='results',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
        migrations.AddField(
            model_name='status',
            name='title',
            field=models.CharField(blank=True, choices=[('На рассмотрении', 'На рассмотрении'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена'), ('Отменена', 'Отменена'), ('Посещено', 'Посещено')], max_length=255, verbose_name='Статус заявки'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.application'),
        ),
        migrations.DeleteModel(
            name='Event_Plan',
        ),
        migrations.DeleteModel(
            name='Event_Plan_Position',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='InvitationStatus',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Team_List',
        ),
        migrations.DeleteModel(
            name='Team_Members',
        ),
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
