# Generated by Django 5.0.6 on 2024-05-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_event_plan_position_event_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.status'),
        ),
    ]
